[build-system]
# Must be kept in sync with `requirements.txt`
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.autopep8]
max_line_length = 120
